# Streamlit secrets.toml

[auth]
admin_id = "jeon080423"
admin_pw = "3033"

[groq]
# 새로 발급받으신 Groq API 키를 여기에 입력하세요
api_key = "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"

[news_api]
api_key = "13cfedc9823541c488732fb27b02fa25"

[gsheet]
# 코드 내에서 SHEET_ID만 따로 쓰는 경우가 많으므로 아래와 같이 관리하면 편리합니다.
sheet_id = "1eu_AeA54pL0Y0axkhpbf5_Ejx0eqdT0oFM3WIepuisU"
url = "https://docs.google.com/spreadsheets/d/1eu_AeA54pL0Y0axkhpbf5_Ejx0eqdT0oFM3WIepuisU/edit?gid=0#gid=0"
