[auth]
admin_id = "jeon080423"
admin_pw = "3033"

[gemini]
api_key = "AIzaSyBZT8GHuD9E9TuhbsZxlRPXxoQfAXNCnV8"

[news_api]
api_key = "13cfedc9823541c488732fb27b02fa25"

gsheet_url = "https://docs.google.com/spreadsheets/d/1eu_AeA54pL0Y0axkhpbf5_Ejx0eqdT0oFM3WIepuisU/edit?gid=0#gid=0"
